first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views


# TEMPLATE TAGGING
app_name = 'first_app'


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$',views.user_login, name='user_login')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special')
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=None)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)


    def __str__(self):
        return self.user.username 



class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=None)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=None)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError('NAME NEEDS TO START WITH Z')

        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')







class FormName( forms.Form ):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('MAKE SURE EMAILS MATCH')
    

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import AccessRecord,Topic,Webpage
from first_app.forms import UserForm, UserProfileInfoForm
from . import forms

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index( request ):
    return render( request, 'first_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
@login_required
def special(request):
    return HttpResponse('YOU ARE LOGGED IN! THANK YOU')



def register( request ):

    registered = False

    if request.method == 'POST':
        user_form = UserForm( data=request.POST)
        profile_form = UserProfileInfoForm( data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save( commit=False )
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print( user_form.errors,profile_form.errors)

    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render( request,'first_app/registration.html',
                                    {
                                        'user_form':user_form,
                                        'profile_form':profile_form,
                                        'registered':registered
                                    })



def form_name_view( request ):
    form = forms.FormName()


    if request.method == "POST":
        form = forms.FormName(request.POST)

        if form.is_valid():
            #DO SOMETHING HERE
            print('VALIDATION SUCCESSFUL !')
            print('NAME: '+form.cleaned_data['name'])
            print('EMAIL: '+form.cleaned_data['email'])
            print('TEXT: '+form.cleaned_data['text'])

    return render( request , 'first_app/form_page.html', {'form':form} )


def user_login( request ):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate( username=username, password=password )

        if user:
            if user.is_active:
                login( request, user )
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')

        else:
            print('Someone tried to login and failed!')
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("Invalid login details  supplied! ")


        
    else:
        return render( request, 'first_app/login.html',{})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
           <div class="container">
               <ul class="nav navbar-nav">
                   <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                   <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                   <li><a class="navbar-link" href="{% url 'first_app:register' %}">Register</a></li>
               
                   {% if user.is_authenticated %}
                   <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                
                   {% else %}
                   <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>
                   {% endif %}
                </ul>
           </div>
        </nav>

        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inherited -->
            {% endblock %}
        </div>
    </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Asha herself</title>
    <link rel="stylesheet" href="{% static 'css/mystyle.css'%}"/>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

      <div class="jumbotron">       
            <h1>Hi, Welcome to Django level 2</h1>
            <h2>Here are your access records:</h2>
            <!-- <img src="{% static 'images/asha.jpg'%}" alt="asha"> -->
      </div>
      <h1>Please fill out the form</h1>
      <div class="container">
          <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit">
          </form>
      </div>
  </body>
</html>

first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}

{% block body_block %}


<div class="jumbotron">
  <h1>Django level five</h1>
</div>


{% endblock %}

first_project/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'first_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="username">

        <label for="password">password:</label>
        <input type="password" name="password">

        <input type="submit" class="btn btn-primary" value="submit">
    </form>
</div>
{% endblock %}

first_project/templates/first_app/registration.html
{% extends "first_app/base.html"%}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering </h1>
      {% else %}
      <h1>Register here</h1>
      <h2>Fill out the form:</h2>

      <form method="POST" enctype="multipart/form-data">
         {{ user_form.as_p }}
         {{ profile_form.as_p }}
         {% csrf_token %}
         <input type="submit" class="btn btn-primary" value="register">
      </form>


    {% endif %}
</div>
{% endblock %}